[package]
name = "michelangelo_core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde_json = "1"
michelangelo_protocol = { path = "../michelangelo_protocol" }
michelangelo_workspace = { path = "../michelangelo_workspace" }
michelangelo_jobs = { path = "../michelangelo_jobs" }
michelangelo_blender = { path = "../michelangelo_blender" }

[dev-dependencies]
tempfile = "3"
