//! Blender job specification, result, capabilities, and operation DTOs.
//!
//! These DTOs define the strict contract between the Rust core and the
//! Blender Python worker. They intentionally exclude arbitrary Python
//! execution or unsafe operations.

use serde::{Deserialize, Serialize};

/// Specification for a Blender job to execute.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BlenderJobSpec {
    /// Human-readable / machine-friendly job type (e.g. `"blender_smoke_scene"`).
    pub job_type: String,
    /// Whether to block until the job completes.
    #[serde(default)]
    pub wait: bool,
    /// Maximum wall-clock time in milliseconds.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub timeout_ms: Option<u64>,
    /// Ordered list of Blender operations to execute.
    pub spec: BlenderSpecBody,
}

/// Inner body of a Blender job spec containing operations.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BlenderSpecBody {
    pub operations: Vec<BlenderOperation>,
}

/// A single safe Blender operation within a job spec.
///
/// The `op` field selects the operation; the remaining fields are
/// operation-specific parameters. Unknown `op` values are rejected by
/// Rust validation or by the Python worker with a structured error.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BlenderOperation {
    /// Operation name (e.g. `"create_box"`, `"set_material"`, `"save_blend"`).
    pub op: String,
    /// Object name (used by create_box, set_material, etc.).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// 3D size vector [x, y, z].
    #[serde(skip_serializing_if = "Option::is_none")]
    pub size: Option<Vec<f64>>,
    /// 3D location vector [x, y, z].
    #[serde(skip_serializing_if = "Option::is_none")]
    pub location: Option<Vec<f64>>,
    /// RGBA color [r, g, b, a] with values 0.0–1.0.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub color: Option<Vec<f64>>,
    /// Target object name (used by set_material).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub object: Option<String>,
    /// Camera view names (used by set_camera_set).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub views: Option<Vec<String>>,
    /// Output file path relative to workspace root.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
}

/// Result produced by a Blender Python worker.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BlenderJobResult {
    /// The job id that was passed to the worker.
    pub job_id: String,
    /// `"completed"`, `"failed"`, or `"cancelled"`.
    pub status: String,
    /// Human-readable summary message.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    /// List of artifact metadata.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub artifacts: Option<Vec<BlenderArtifactDto>>,
    /// Scene introspection summary (triangles, objects, materials).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub scene_summary: Option<serde_json::Value>,
    /// Structured error information if status is `"failed"`.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
}

/// Describes an artifact generated by a Blender job.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BlenderArtifactDto {
    /// Path relative to the workspace project root.
    pub path: String,
    /// Artifact type (e.g. `"blend"`, `"glb"`, `"png"`).
    #[serde(rename = "type")]
    pub artifact_type: String,
    /// File size in bytes.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub size_bytes: Option<u64>,
}

/// Describes the capabilities of the configured Blender executable.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BlenderCapabilitiesDto {
    /// Blender version string (from `blender --version`).
    pub blender_version: String,
    /// Whether `bpy` is importable (i.e. headless background mode works).
    pub bpy_available: bool,
    /// List of safe worker operation names supported by the installed worker.
    pub supported_operations: Vec<String>,
    /// Whether the Blender binary was found at the configured path.
    pub binary_found: bool,
}

impl BlenderCapabilitiesDto {
    /// Create an empty/unavailable capabilities descriptor.
    pub fn unavailable() -> Self {
        Self {
            blender_version: String::new(),
            bpy_available: false,
            supported_operations: Vec::new(),
            binary_found: false,
        }
    }
}

/// The set of safe operations accepted by the Blender worker in Phase 2.
pub const SAFE_WORKER_OPS: &[&str] = &[
    "create_box",
    "set_material",
    "set_camera_set",
    "render_views",
    "export_glb",
    "save_blend",
    "get_scene_summary",
];

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_blender_job_spec_serializes() {
        let spec = BlenderJobSpec {
            job_type: "blender_smoke_scene".into(),
            wait: true,
            timeout_ms: Some(180_000),
            spec: BlenderSpecBody {
                operations: vec![BlenderOperation {
                    op: "create_box".into(),
                    name: Some("body".into()),
                    size: Some(vec![2.0, 1.0, 0.5]),
                    location: Some(vec![0.0, 0.0, 0.0]),
                    color: None,
                    object: None,
                    views: None,
                    path: None,
                }],
            },
        };
        let json = serde_json::to_string(&spec).unwrap();
        assert!(json.contains(r#""job_type":"blender_smoke_scene""#));
        assert!(json.contains(r#""wait":true"#));
        assert!(json.contains(r#""timeout_ms":180000"#));
        assert!(json.contains(r#""op":"create_box""#));
        assert!(json.contains(r#""name":"body""#));
    }

    #[test]
    fn test_blender_job_spec_deserializes() {
        let json = r#"{
            "job_type": "blender_smoke_scene",
            "wait": true,
            "timeout_ms": 180000,
            "spec": {
                "operations": [
                    {"op": "create_box", "name": "body", "size": [2.0, 1.0, 0.5], "location": [0.0, 0.0, 0.0]},
                    {"op": "set_material", "object": "body", "color": [0.2, 0.4, 0.8, 1.0]},
                    {"op": "save_blend", "path": "blender/scenes/smoke_v001.blend"},
                    {"op": "export_glb", "path": "blender/exports/smoke_v001.glb"}
                ]
            }
        }"#;
        let spec: BlenderJobSpec = serde_json::from_str(json).unwrap();
        assert_eq!(spec.job_type, "blender_smoke_scene");
        assert!(spec.wait);
        assert_eq!(spec.timeout_ms, Some(180_000));
        assert_eq!(spec.spec.operations.len(), 4);
        assert_eq!(spec.spec.operations[0].op, "create_box");
        assert_eq!(spec.spec.operations[1].op, "set_material");
        assert_eq!(spec.spec.operations[3].op, "export_glb");
        assert_eq!(
            spec.spec.operations[3].path.as_deref(),
            Some("blender/exports/smoke_v001.glb")
        );
    }

    #[test]
    fn test_blender_operation_roundtrip() {
        let op = BlenderOperation {
            op: "set_material".into(),
            name: None,
            size: None,
            location: None,
            color: Some(vec![0.2, 0.4, 0.8, 1.0]),
            object: Some("body".into()),
            views: None,
            path: None,
        };
        let json = serde_json::to_string(&op).unwrap();
        let decoded: BlenderOperation = serde_json::from_str(&json).unwrap();
        assert_eq!(decoded.op, "set_material");
        assert_eq!(decoded.object.as_deref(), Some("body"));
        assert_eq!(decoded.color, Some(vec![0.2, 0.4, 0.8, 1.0]));
    }

    #[test]
    fn test_blender_job_result_serializes() {
        let result = BlenderJobResult {
            job_id: "job_blender_001".into(),
            status: "completed".into(),
            message: Some("Smoke test done".into()),
            artifacts: Some(vec![BlenderArtifactDto {
                path: "blender/scenes/smoke_v001.blend".into(),
                artifact_type: "blend".into(),
                size_bytes: Some(42_000),
            }]),
            scene_summary: Some(serde_json::json!({"objects": 3, "triangles": 24})),
            error: None,
        };
        let json = serde_json::to_string(&result).unwrap();
        assert!(json.contains(r#""job_id":"job_blender_001""#));
        assert!(json.contains(r#""status":"completed""#));
        assert!(json.contains(r#""path":"blender/scenes/smoke_v001.blend""#));
        assert!(json.contains(r#""objects":3"#));
    }

    #[test]
    fn test_blender_job_result_failure() {
        let result = BlenderJobResult {
            job_id: "job_fail_001".into(),
            status: "failed".into(),
            message: Some("Unknown operation: explode".into()),
            artifacts: None,
            scene_summary: None,
            error: Some("Operation 'explode' is not in the safe set".into()),
        };
        let json = serde_json::to_string(&result).unwrap();
        assert!(json.contains(r#""status":"failed""#));
        assert!(json.contains(r#""error":"#));
    }

    #[test]
    fn test_blender_capabilities_serializes() {
        let caps = BlenderCapabilitiesDto {
            blender_version: "4.0.2".into(),
            bpy_available: true,
            supported_operations: SAFE_WORKER_OPS.iter().map(|s| (*s).to_string()).collect(),
            binary_found: true,
        };
        let json = serde_json::to_string(&caps).unwrap();
        assert!(json.contains(r#""blender_version":"4.0.2""#));
        assert!(json.contains(r#""bpy_available":true"#));
        assert!(json.contains(r#""create_box""#));
    }

    #[test]
    fn test_blender_capabilities_unavailable() {
        let caps = BlenderCapabilitiesDto::unavailable();
        assert!(!caps.binary_found);
        assert!(!caps.bpy_available);
        assert!(caps.blender_version.is_empty());
        assert!(caps.supported_operations.is_empty());
    }

    #[test]
    fn test_safe_worker_ops_are_known() {
        assert!(SAFE_WORKER_OPS.contains(&"create_box"));
        assert!(SAFE_WORKER_OPS.contains(&"save_blend"));
        assert!(SAFE_WORKER_OPS.contains(&"export_glb"));
        assert!(!SAFE_WORKER_OPS.contains(&"execute_arbitrary_python"));
    }

    #[test]
    fn test_blender_artifact_dto_type_alias() {
        let artifact = BlenderArtifactDto {
            path: "output/render.png".into(),
            artifact_type: "png".into(),
            size_bytes: None,
        };
        let json = serde_json::to_string(&artifact).unwrap();
        assert!(json.contains(r#""type":"png""#));
        assert!(!json.contains("artifact_type"));
    }
}
